import { type NextRequest, NextResponse } from "next/server"

// Datos de productos de ejemplo (después conectarás a BD)
const PRODUCTS = [
  {
    id: 1,
    name: "Taladro Profesional DeWalt 20V",
    slug: "taladro-dewalt-20v",
    description: "Taladro inalámbrico profesional de alto rendimiento",
    price: 149.99,
    originalPrice: 199.99,
    category: "taladros",
    image: "/professional-drill.jpg",
    thumbnail: "/professional-drill.jpg",
    rating: 4.8,
    stock: 50,
    brand: "DeWalt",
    specs: {
      voltaje: "20V",
      velocidad: "0-500 RPM",
      capacidad: "13mm",
      peso: "1.5kg",
    },
  },
  {
    id: 2,
    name: 'Sierra Circular Makita 7 1/4"',
    slug: "sierra-circular-makita",
    description: "Sierra circular de 7 1/4 pulgadas con potencia máxima",
    price: 89.99,
    originalPrice: 129.99,
    category: "sierras",
    image: "/circular-saw-makita.jpg",
    thumbnail: "/circular-saw.png",
    rating: 4.6,
    stock: 35,
    brand: "Makita",
    specs: {
      potencia: "5800W",
      velocidad: "5800 RPM",
      profundidad: "57mm",
      peso: "2.3kg",
    },
  },
  {
    id: 3,
    name: 'Lijadora Orbital Bosch 5"',
    slug: "lijadora-orbital-bosch",
    description: "Lijadora orbital profesional de precisión",
    price: 79.99,
    originalPrice: 119.99,
    category: "lijadoras",
    image: "/orbital-sander-bosch.jpg",
    thumbnail: "/orbital-sander.png",
    rating: 4.7,
    stock: 42,
    brand: "Bosch",
    specs: {
      potencia: "350W",
      velocidad: "12000 opm",
      tamaño: "5 pulgadas",
      peso: "1.1kg",
    },
  },
  {
    id: 4,
    name: "Juego 40 Destornilladores",
    slug: "juego-destornilladores",
    description: "Set completo de 40 destornilladores profesionales",
    price: 34.99,
    originalPrice: 49.99,
    category: "destornilladores",
    image: "/screwdriver-set-professional.jpg",
    thumbnail: "/screwdriver-set.jpg",
    rating: 4.9,
    stock: 100,
    brand: "Stanley",
    specs: {
      cantidad: "40 piezas",
      tipos: "Phillips, Slotted, Square",
      estuche: "Incluido",
    },
  },
  {
    id: 5,
    name: "Mazo de Goma 32oz",
    slug: "mazo-goma-32oz",
    description: "Mazo profesional de goma de alta calidad",
    price: 15.99,
    originalPrice: 24.99,
    category: "herramientas-manuales",
    image: "/rubber-mallet-hammer.jpg",
    thumbnail: "/rubber-mallet.jpg",
    rating: 4.8,
    stock: 80,
    brand: "Estwing",
    specs: {
      peso: "32oz (907g)",
      material: "Goma de nylon",
      mango: "Acero templado",
    },
  },
  {
    id: 6,
    name: "Casco de Seguridad Amarillo",
    slug: "casco-amarillo",
    description: "Casco profesional ANSI certificado",
    price: 12.99,
    originalPrice: 19.99,
    category: "seguridad",
    image: "/yellow-safety-helmet.jpg",
    thumbnail: "/yellow-safety-helmet.png",
    rating: 4.7,
    stock: 200,
    brand: "3M",
    specs: {
      certificacion: "ANSI Z89.1",
      material: "ABS",
      peso: "400g",
    },
  },
  {
    id: 7,
    name: "Martillo Perforador SDS Bosch",
    slug: "martillo-perforador-bosch",
    description: "Martillo perforador profesional con sistema SDS",
    price: 189.99,
    originalPrice: 269.99,
    category: "Herramientas varias",
    image: "/logo-debandi.svg",
    thumbnail: "/logo-debandi.svg",
    rating: 4.8,
    stock: 28,
    brand: "Bosch",
    specs: {
      potencia: "800W",
      velocidad: "1300 RPM",
      impactos: "7800 ipm",
      peso: "2.4kg",
    },
  },
  {
    id: 8,
    name: "Sierra Alternante DeWalt",
    slug: "sierra-alternante-dewalt",
    description: "Sierra alternante potente para cortes precisos",
    price: 125.99,
    originalPrice: 179.99,
    category: "Herramientas varias",
    image: "/logo-debandi.svg",
    thumbnail: "/logo-debandi.svg",
    rating: 4.6,
    stock: 32,
    brand: "DeWalt",
    specs: {
      potencia: "920W",
      carrera: "28mm",
      velocidad: "3000 spm",
      peso: "2.1kg",
    },
  },
  {
    id: 9,
    name: "Motosierra Makita 45cc",
    slug: "motosierra-makita",
    description: "Motosierra de gasolina de alto rendimiento",
    price: 329.99,
    originalPrice: 449.99,
    category: "Riego y jardin",
    image: "/logo-debandi.svg",
    thumbnail: "/logo-debandi.svg",
    rating: 4.7,
    stock: 15,
    brand: "Makita",
    specs: {
      cilindrada: "45cc",
      potencia: "2.4kW",
      capacidad: "0.45L",
      peso: "4.9kg",
    },
  },
  {
    id: 10,
    name: "Compresor de Aire Stanley 50L",
    slug: "compresor-stanley",
    description: "Compresor de aire profesional con tanque de 50 litros",
    price: 159.99,
    originalPrice: 229.99,
    category: "Herramientas varias",
    image: "/logo-debandi.svg",
    thumbnail: "/logo-debandi.svg",
    rating: 4.5,
    stock: 20,
    brand: "Stanley",
    specs: {
      capacidad: "50L",
      presion: "8 bar",
      potencia: "2.2kW",
      peso: "45kg",
    },
  },
  {
    id: 11,
    name: "Juego de Brocas Profesional 101pz",
    slug: "juego-brocas-profesional",
    description: "Set de 101 brocas de acero de alta velocidad",
    price: 29.99,
    originalPrice: 44.99,
    category: "Tornilleria",
    image: "/logo-debandi.svg",
    thumbnail: "/logo-debandi.svg",
    rating: 4.6,
    stock: 120,
    brand: "Bosch",
    specs: {
      cantidad: "101 piezas",
      material: "Acero HSS",
      estuche: "Caja metálica",
    },
  },
  {
    id: 12,
    name: "Guantes de Trabajo Nitrilo",
    slug: "guantes-nitrilo",
    description: "Guantes de protección con agarre mejorado",
    price: 8.99,
    originalPrice: 12.99,
    category: "Seguridad",
    image: "/logo-debandi.svg",
    thumbnail: "/logo-debandi.svg",
    rating: 4.4,
    stock: 500,
    brand: "Ansell",
    specs: {
      material: "Nitrilo",
      talles: "XS-XXL",
      cantidad: "Par",
    },
  },
  {
    id: 13,
    name: "Lentes de Seguridad Anti-reflejo",
    slug: "lentes-seguridad",
    description: "Lentes protectores con lentes anti-reflejo",
    price: 18.99,
    originalPrice: 27.99,
    category: "Seguridad",
    image: "/logo-debandi.svg",
    thumbnail: "/logo-debandi.svg",
    rating: 4.5,
    stock: 150,
    brand: "Uvex",
    specs: {
      certificacion: "ANSI Z87.1",
      lentes: "Policarbonato",
      proteccion: "UV",
    },
  },
  {
    id: 14,
    name: "Nivel Láser Digital Bosch 30m",
    slug: "nivel-laser-bosch",
    description: "Nivel láser digital con alcance de 30 metros",
    price: 89.99,
    originalPrice: 129.99,
    category: "Ferreteria",
    image: "/logo-debandi.svg",
    thumbnail: "/logo-debandi.svg",
    rating: 4.7,
    stock: 45,
    brand: "Bosch",
    specs: {
      alcance: "30m",
      precision: "±3mm/10m",
      bateria: "AA x 4",
      peso: "470g",
    },
  },
  {
    id: 15,
    name: "Linterna LED Profesional 1000 lum",
    slug: "linterna-led-profesional",
    description: "Linterna LED de alta potencia 1000 lúmenes",
    price: 34.99,
    originalPrice: 49.99,
    category: "Electricidad",
    image: "/logo-debandi.svg",
    thumbnail: "/logo-debandi.svg",
    rating: 4.8,
    stock: 80,
    brand: "Streamlight",
    specs: {
      potencia: "1000 lúmenes",
      alcance: "200m",
      bateria: "2x 18650",
      peso: "240g",
    },
  },
  {
    id: 16,
    name: "Escalera Telescópica Aluminio 4.7m",
    slug: "escalera-telescopica",
    description: "Escalera telescópica de aluminio con estabilizador",
    price: 109.99,
    originalPrice: 159.99,
    category: "Ferreteria",
    image: "/logo-debandi.svg",
    thumbnail: "/logo-debandi.svg",
    rating: 4.6,
    stock: 25,
    brand: "Werner",
    specs: {
      altura: "4.7m",
      material: "Aluminio",
      carga: "150kg",
      peso: "11kg",
    },
  },
  {
    id: 17,
    name: "Llave Inglesa Ajustable",
    slug: "llave-inglesa-ajustable",
    description: "Llave inglesa de alta calidad 300mm",
    price: 14.99,
    originalPrice: 21.99,
    category: "Herramientas varias",
    image: "/logo-debandi.svg",
    thumbnail: "/logo-debandi.svg",
    rating: 4.5,
    stock: 200,
    brand: "Stanley",
    specs: {
      longitud: "300mm",
      material: "Acero vanadio",
      boca: "0-35mm",
    },
  },
  {
    id: 18,
    name: "Pistola Caladora Inalámbrica",
    slug: "pistola-caladora-inalambrica",
    description: "Caladora inalámbrica con batería de 20V",
    price: 99.99,
    originalPrice: 149.99,
    category: "Herramientas varias",
    image: "/logo-debandi.svg",
    thumbnail: "/logo-debandi.svg",
    rating: 4.7,
    stock: 38,
    brand: "DeWalt",
    specs: {
      voltaje: "20V",
      carrera: "10mm",
      velocidad: "3000 spm",
      peso: "2.3kg",
    },
  },
  {
    id: 19,
    name: "Cinta Métrica de Fibra 10m",
    slug: "cinta-metrica-fibra",
    description: "Cinta métrica profesional de 10 metros",
    price: 11.99,
    originalPrice: 17.99,
    category: "Ferreteria",
    image: "/logo-debandi.svg",
    thumbnail: "/logo-debandi.svg",
    rating: 4.6,
    stock: 250,
    brand: "Stanley",
    specs: {
      longitud: "10m",
      ancho: "25mm",
      material: "Fibra",
      estuche: "Plástico",
    },
  },
  {
    id: 20,
    name: "Soldador MMA 160A Portátil",
    slug: "soldador-mma-160a",
    description: "Soldador tipo inverter compacto y portátil",
    price: 249.99,
    originalPrice: 349.99,
    category: "Herramientas varias",
    image: "/logo-debandi.svg",
    thumbnail: "/logo-debandi.svg",
    rating: 4.8,
    stock: 12,
    brand: "Esab",
    specs: {
      amperaje: "160A",
      voltaje: "220V",
      tipo: "Inverter IGBT",
      peso: "5.5kg",
    },
  },
  {
    id: 21,
    name: "Bomba de Agua Sumergible 750W",
    slug: "bomba-agua-sumergible",
    description: "Bomba sumergible profesional para aguas claras",
    price: 79.99,
    originalPrice: 119.99,
    category: "Agua",
    image: "/logo-debandi.svg",
    thumbnail: "/logo-debandi.svg",
    rating: 4.5,
    stock: 35,
    brand: "Makita",
    specs: {
      potencia: "750W",
      caudal: "200 L/min",
      profundidad: "7m",
      peso: "3.2kg",
    },
  },
  {
    id: 22,
    name: "Cilindro de Gas Propano 10kg",
    slug: "cilindro-gas-propano-10kg",
    description: "Cilindro de gas propano para uso industrial",
    price: 24.99,
    originalPrice: 34.99,
    category: "Gas",
    image: "/logo-debandi.svg",
    thumbnail: "/logo-debandi.svg",
    rating: 4.6,
    stock: 60,
    brand: "Ultragás",
    specs: {
      capacidad: "10kg",
      presion: "5 bar",
      tipo: "Propano",
    },
  },
  {
    id: 23,
    name: "Adhesivo Epoxi Profesional 500ml",
    slug: "adhesivo-epoxi-profesional",
    description: "Adhesivo epoxi de dos componentes de máxima dureza",
    price: 18.99,
    originalPrice: 27.99,
    category: "Quimicos y adhesivos",
    image: "/logo-debandi.svg",
    thumbnail: "/logo-debandi.svg",
    rating: 4.7,
    stock: 150,
    brand: "Loctite",
    specs: {
      volumen: "500ml",
      tiempo_secado: "24 horas",
      resistencia: "Temperatura alta",
    },
  },
  {
    id: 24,
    name: "Bombilla LED 9W E27 Cálida",
    slug: "bombilla-led-9w-e27",
    description: "Bombilla LED de bajo consumo luz cálida",
    price: 9.99,
    originalPrice: 14.99,
    category: "Hogar",
    image: "/logo-debandi.svg",
    thumbnail: "/logo-debandi.svg",
    rating: 4.8,
    stock: 300,
    brand: "Philips",
    specs: {
      potencia: "9W",
      casquillo: "E27",
      temperatura: "3000K",
      duracion: "25000 horas",
    },
  },
  {
    id: 25,
    name: "Tornillos Cabeza Plana Caja 500pz",
    slug: "tornillos-cabeza-plana-500",
    description: "Caja de 500 tornillos de cabeza plana",
    price: 12.99,
    originalPrice: 18.99,
    category: "Tornilleria",
    image: "/logo-debandi.svg",
    thumbnail: "/logo-debandi.svg",
    rating: 4.5,
    stock: 50,
    brand: "Stanley",
    specs: {
      cantidad: "500 piezas",
      medida: "3.5x25mm",
      material: "Acero zincado",
    },
  },
  {
    id: 26,
    name: "Producto Sin Categoría",
    slug: "producto-sin-categoria",
    description: "Producto a la espera de categorización",
    price: 5.99,
    originalPrice: 9.99,
    category: "Sin definir",
    image: "/logo-debandi.svg",
    thumbnail: "/logo-debandi.svg",
    rating: 3.5,
    stock: 25,
    brand: "Genérico",
    specs: {
      estado: "Pendiente",
      notas: "Requiere categorización",
    },
  },
]

export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams
  const category = searchParams.get("category")
  const search = searchParams.get("search")
  const page = Number.parseInt(searchParams.get("page") || "1")
  const limit = 30

  let filtered = [...PRODUCTS]

  if (category && category !== "all") {
    filtered = filtered.filter((p) => p.category === category)
  }

  if (search) {
    const searchLower = search.toLowerCase()
    filtered = filtered.filter(
      (p) =>
        p.name.toLowerCase().includes(searchLower) ||
        p.description.toLowerCase().includes(searchLower) ||
        (p.brand?.toLowerCase().includes(searchLower) || false),
    )
  }

  const total = filtered.length
  const start = (page - 1) * limit
  const paginated = filtered.slice(start, start + limit)

  return NextResponse.json({
    products: paginated,
    total,
    pages: Math.ceil(total / limit),
    currentPage: page,
  })
}
